### ISSUE TITLE
tabular data/ noisy instances

### ISSUE THREAD

**Issue by nazaretl** [youjiangxu/FaMUS#4]
Hi,
thanks for sharing your implementation. I have two questions about it:

1. Does it also work on tabular data?
2. Is is possible to identify the noisy instances (return the noisy IDs or the clean set)

Thanks!

**Comment by youjiangxu** [comment]
> Hi, thanks for sharing your implementation. I have two questions about it:
> 
> 1. Does it also work on tabular data?
> 2. Is is possible to identify the noisy instances (return the noisy IDs or the clean set)
> 
> Thanks!

Hi nazaretl,

1. We believe that our method can learn a robust model from data with noisy labels. If the tabular data contains noisy labels, FaMUS maybe work in this area. However, We have not conducted experiments with tabular data before, so we are not quite sure about it.  
2. The noisy instance can be identified by the two-component GMM model with a predefined threshold. 

Hope our reply can solve your question.

Thank you very much!

**Comment by nazaretl** [comment]
I see, thank you for the response!
